### ISSUE TITLE
Why do you use MyBatis

### ISSUE THREAD

**Issue by HelloTo4x** [yiding-he/hybatis#1]
Hi, why do you use MyBatis instead of Hibernate, JPA ?, why do you choose it in your project, can u tell me the Mybatis 's pros and cons

**Comment by yiding-he** [comment]
@HelloTo4x 
没别的意思，MyBatis 是工作内容需要，是综合考虑的结果。如果只凭我个人兴趣，spring-data-jdbc 应该是首选吧。这个项目的目的是看能不能封装一部分 MyBatis 使用方面的重复工作。MyBatisPlus 在这方面做的不够。

**Comment by yiding-he** [comment]
@HelloTo4x 参考 https://xie.infoq.cn/article/bf2eeedbfb58acc8ef9c27b20
